# General Variable names
contractDate.name <- "CONTRACT DATE" 
setupDate.name <- "SETUP DATE" 
originalLoanAmount.name <- "ORIGINAL LOAN AMOUNT"
originalTerm.name <- "ORIGINAL TERM" 
originalMaturityDate.name <-  "ORIGINAL MATURITY DATE"  
currentMaturityDate.name <- "CURRENT MATURITY DATE" 
interestRate.name <- "INTEREST RATE"  
creditScoreCurrentHigh.name <- "CREDIT SCORE CURRENT HIGH"
creditScore.name <- "CREDIT SCORE"  
creditScoreName2.name <- "CREDIT SCORE NAME 2"
debtToIncome.name <-  "DEBT TO INCOME" 
firstPaymentDate.name <- "FIRST PAYMENT DATE" 
lastPaymentDate.name <- "LAST PAYMENT DATE"
nextPaymentDueDate.name <- "NEXT PAYMENT DUE DATE" 
paymentAmount.name <- "PAYMENT AMOUNT"  
currentBalance.name <- "CURRENT BALANCE" 
unappliedCash.name <- "UNAPPLIED CASH" 
delinquentAmount.name <- "DELINQUENT AMOUNT" 
totalInterestPaid.name <- "TOTAL INTEREST PAID"
totalLateChargePaid.name <- "TOTAL LATE CHARGE PAID" 
paymentsRemaining.name <- "PAYMENTS REMAINING"    
daysDelinquent.name <-  "DAYS DELINQUENT" 
propertyCounty.name <- "PROPERTY COUNTY" 
utility.name <-  "UTILITY"     
installationCity.name <-  "INSTALLATION CITY"
installationZip.name <-  "INSTALLATION ZIP" 
accountCode.name <-  "ACCOUNT CODE" 
accountCodeDate.name <-  "ACCOUNT CODE DATE"
cancelReason.name <- "CANCEL REASON" 
typeOfBankruptcy.name <- "TYPE OF BANKRUPTCY" 
monthSinceOrigination.name <- "Months Since Origination"
paymentMade.name <- "Payments Made" 
purpose.name <- "Purpose"
loanType.name <- "Loan Type" 
underWriting.name <-  "Underwriting"
pledged.name <- "Pledged"
georeference.name <-  "Georeference" 

ORIGINAL_LOAN_AMOUNT_NAME= "ORIGINAL_LOAN_AMOUNT"
INTEREST_RATE_NAME = "INTEREST_RATE"
DEBT_TO_INCOME_NAME = "DEBT_TO_INCOME"
CREDIT_SCORE_NAME = "CREDIT_SCORE"
DEBT_TO_INCOME = "DEBT_TO_INCOME"
DAYS_DELINQUENT_NAME = "DAYS_DELINQUENT"
PROPERTY_COUNTY = "PROPERTY_COUNTY"
Purpose_NAME= "Purpose"
Loan_Type_NAME = "Loan Type"
ORIGINAL_TERM_NAME = "ORIGINAL_TERM"


id.name <- "record_id"
year.name <- "CONTRACT YEAR"
city.name <- "INSTALLATION CITY"

# PP variable names
avgLoans.name <- "Average number of loans"
avgLoanAmouunt.name <- "Average loan amount"
avgInterestRate.name <- "Average interest rate"
avgdelinquentAmount.name <- "Average delinquent amount"
